"""Financial engine nightmare scenarios — journal entries, depreciation,
trial balance, accruals, multi-currency, intercompany eliminations."""
from __future__ import annotations

import random
from decimal import Decimal
from typing import Any


FINANCIAL_SPECS: list[dict[str, Any]] = [
    {
        "subtype": "je_500_lines_must_balance",
        "difficulty": "nightmare",
        "description": "Journal entry with 500 debit/credit lines — must balance to the cent",
        "input": {"lines": 500, "inject_imbalance": False},
        "expected": {"balanced": True, "delta": "0.00"},
        "severity_on_failure": "critical",
    },
    {
        "subtype": "je_500_lines_off_by_penny",
        "difficulty": "nightmare",
        "description": "500-line JE with 1¢ imbalance — must be rejected",
        "input": {"lines": 500, "inject_imbalance": True, "imbalance_cents": 1},
        "expected": {"balanced": False, "delta": "0.01"},
        "severity_on_failure": "critical",
    },
    {
        "subtype": "multi_currency_historical_vs_current_fx",
        "difficulty": "nightmare",
        "description": "Multi-currency JE: historical rate for asset, current rate for translation",
        "input": {"currencies": ["USD", "CAD", "EUR"], "historical_usd_cad": 1.25, "current_usd_cad": 1.37},
        "expected": {"translation_gain_loss_required": True},
        "severity_on_failure": "high",
    },
    {
        "subtype": "depreciation_across_fy_change",
        "difficulty": "hard",
        "description": "Depreciation schedule spanning a fiscal year-end change",
        "input": {"asset_cost": "10000.00", "useful_life_years": 5, "fy_end_change": True},
        "expected": {"proration_required": True},
        "severity_on_failure": "high",
    },
    {
        "subtype": "period_close_accruals_straddling",
        "difficulty": "hard",
        "description": "Accrual straddling two months — reversal must post",
        "input": {"accrual_date": "2026-03-31", "reverse_date": "2026-04-01"},
        "expected": {"reversal_posted": True},
        "severity_on_failure": "high",
    },
    {
        "subtype": "trial_balance_1000_accounts",
        "difficulty": "nightmare",
        "description": "Trial balance across 1000 GL accounts — should compute in <5s",
        "input": {"account_count": 1000},
        "expected": {"performance_seconds_max": 5.0, "balanced": True},
        "severity_on_failure": "medium",
    },
    {
        "subtype": "prior_year_reclassification",
        "difficulty": "hard",
        "description": "Reclassify prior-year entries — opening balances must update",
        "input": {"target_year": 2025, "reclass_amount": "5000.00"},
        "expected": {"opening_balance_changed": True},
        "severity_on_failure": "high",
    },
    {
        "subtype": "prepaid_12_month_amortization",
        "difficulty": "normal",
        "description": "Prepaid insurance amortized over 12 months — each month 1/12",
        "input": {"prepaid_total": "12000.00", "months": 12},
        "expected": {"monthly_expense": "1000.00", "schedule_length": 12},
        "severity_on_failure": "medium",
    },
    {
        "subtype": "inventory_fifo_valuation",
        "difficulty": "hard",
        "description": "FIFO inventory valuation across 100 in/out movements",
        "input": {"movements": 100, "method": "FIFO"},
        "expected": {"method": "FIFO", "consistent": True},
        "severity_on_failure": "high",
    },
    {
        "subtype": "intercompany_elimination",
        "difficulty": "nightmare",
        "description": "Intercompany AR/AP must eliminate on consolidation",
        "input": {"parent_ar": "10000.00", "sub_ap": "10000.00"},
        "expected": {"consolidated_net": "0.00"},
        "severity_on_failure": "high",
    },
    {
        "subtype": "tax_provision_timing_diff",
        "difficulty": "nightmare",
        "description": "Tax provision with timing differences (deferred tax)",
        "input": {"book_income": "100000.00", "tax_income": "95000.00", "rate": 0.265},
        "expected": {"deferred_tax_line_required": True},
        "severity_on_failure": "high",
    },
    {
        "subtype": "decimal_precision_rounding",
        "difficulty": "hard",
        "description": "Tax calc at 14.975% must round half-up to cents, not banker's",
        "input": {"amount": "33.33"},
        "expected": {"rounding_mode": "ROUND_HALF_UP"},
        "severity_on_failure": "high",
    },
    {
        "subtype": "negative_retained_earnings",
        "difficulty": "normal",
        "description": "Retained earnings goes negative — still must balance",
        "input": {"net_loss": "50000.00"},
        "expected": {"balanced": True, "re_sign": "negative"},
        "severity_on_failure": "medium",
    },
    {
        "subtype": "je_unbalanced_debits_credits",
        "difficulty": "nightmare",
        "description": "User attempts unbalanced JE — system must reject",
        "input": {"debit_total": "1000.00", "credit_total": "999.99"},
        "expected": {"rejected": True},
        "severity_on_failure": "critical",
    },
    {
        "subtype": "currency_rounding_exchange",
        "difficulty": "hard",
        "description": "USD → CAD conversion with rounding — bookkeeping integrity",
        "input": {"usd_amount": "100.00", "fx_rate": "1.3718"},
        "expected": {"cad_amount": "137.18"},
        "severity_on_failure": "medium",
    },
    {
        "subtype": "bank_reconciliation_off_by_cent",
        "difficulty": "nightmare",
        "description": "Bank rec with 1¢ unreconciled — must flag, not auto-close",
        "input": {"bank_balance": "10000.00", "book_balance": "9999.99"},
        "expected": {"flagged": True, "delta": "0.01"},
        "severity_on_failure": "critical",
    },
    {
        "subtype": "balance_sheet_does_not_balance",
        "difficulty": "nightmare",
        "description": "Injected BS mismatch — A != L+E — must surface",
        "input": {"assets": "100000.00", "liab_equity": "99990.00"},
        "expected": {"balanced": False},
        "severity_on_failure": "critical",
    },
    {
        "subtype": "cashflow_indirect_method",
        "difficulty": "hard",
        "description": "Indirect cash flow — working capital adjustments",
        "input": {"net_income": "50000.00", "ar_change": "-5000.00", "ap_change": "3000.00"},
        "expected": {"method": "indirect"},
        "severity_on_failure": "medium",
    },
    {
        "subtype": "revenue_recognition_deferred",
        "difficulty": "hard",
        "description": "Deferred revenue — recognize ratably over 12 months",
        "input": {"contract_value": "12000.00", "months": 12},
        "expected": {"monthly_recognition": "1000.00"},
        "severity_on_failure": "medium",
    },
    {
        "subtype": "gl_account_mismatch_to_fs",
        "difficulty": "hard",
        "description": "GL account mapped wrongly — ends up on wrong FS line",
        "input": {"account_code": "5000", "mapped_to": "Cost of Sales", "expected_mapping": "Operating Expenses"},
        "expected": {"mismatch_flagged": True},
        "severity_on_failure": "high",
    },
    {
        "subtype": "payroll_ytd_rollover",
        "difficulty": "hard",
        "description": "Year-end payroll YTD rollover — new year starts at zero",
        "input": {"prior_year_ytd": "50000.00", "new_year": 2027},
        "expected": {"new_ytd_starts_at_zero": True},
        "severity_on_failure": "high",
    },
    {
        "subtype": "fixed_asset_disposal_gain_loss",
        "difficulty": "hard",
        "description": "Sell asset below NBV — must record loss on disposal",
        "input": {"nbv": "5000.00", "sale_price": "3000.00"},
        "expected": {"loss_on_disposal": "2000.00"},
        "severity_on_failure": "high",
    },
    {
        "subtype": "aging_bucket_edge_case",
        "difficulty": "normal",
        "description": "AR aging — invoice dated exactly 30 days ago",
        "input": {"invoice_date_days_ago": 30},
        "expected": {"bucket": "31-60"},
        "severity_on_failure": "low",
    },
    {
        "subtype": "segmented_reporting",
        "difficulty": "hard",
        "description": "Multi-department P&L — department totals must sum to entity",
        "input": {"departments": 5},
        "expected": {"sum_matches_entity": True},
        "severity_on_failure": "medium",
    },
    {
        "subtype": "cas_lead_sheet_required",
        "difficulty": "normal",
        "description": "CAS review engagement — lead sheet required for material accounts",
        "input": {"account": "Cash", "balance": "250000.00"},
        "expected": {"lead_sheet_required": True},
        "severity_on_failure": "medium",
    },
]


def generate(rnd: random.Random) -> list[dict[str, Any]]:
    out: list[dict[str, Any]] = []
    for spec in FINANCIAL_SPECS:
        out.append({
            "category": "financial",
            "subtype": spec["subtype"],
            "difficulty": spec["difficulty"],
            "description": spec["description"],
            "severity_on_failure": spec["severity_on_failure"],
            "affects_engines": [
                "src.engines.audit_engine",
                "src.engines.multicurrency_engine",
                "src.engines.fixed_assets_engine",
                "src.engines.payroll_engine",
                "src.engines.cashflow_engine",
                "src.engines.cas_engine",
                "src.engines.aging_engine",
            ],
            "oracle": "financial",
            "input_spec": {"kind": "financial", **spec["input"]},
            "ground_truth": spec["expected"],
        })
    return out
